config_path: null
output_dir: null
dataset_path: data/test
seed: 42
batch_size: 8
num_workers: 10
max_new_tokens: 1024
generation_config:
  do_sample: false
use_regex: true
model_config:
  project_name: null
  run_name: null
  seed: 42
  local_rank: -1
  liger_kernel: true
  model:
    device: cuda
    model_id: llava-hf/llava-1.5-7b-hf
    encoder_id: facebook/dinov2-large
    share_vit: false
    use_depth: true
    depth_model_id: depth-anything/Depth-Anything-V2-Small-hf
    use_segmentation: true
    segmentation_model_id: shi-labs/oneformer_ade20k_dinat_large
    fuser_id: gemini
    conditional_fuser: true
    condition_dropout: 0.3
    no_lora_but_FF_prefix:
    - multi_modal_projector
    - fuser
    - vision_tower.AdaLNZero
    - auxiliary_projectors
    patch_size: 14
    vision_feature_select_strategy: full
    gradient_checkpointing: true
    lora_config:
      r: 256
      lora_alpha: 32
      use_rslora: true
      target_modules:
      - q_proj
      - v_proj
      - multi_modal_projector.linear_1
      - multi_modal_projector.linear_2
      exclude_modules: vision_tower.*
      lora_dropout: 0.3
      use_dora: true
      bias: none
      task_type: CAUSAL_LM
  pipeline:
    wandb: true
    debug: false
  dataset:
    dataset_path: data
    seed: 42
    num_workers: 10
    prefetch_factor: 2
  optimization:
    epochs: 1
    lr: 0.0005
    batch_size: 4
    optimizer_type: default
    accumulation_steps: 4
    gradient_clip_val: 1.0
model_path: null
