gradient_clipping: 1.0
bf16:
  enabled: true
flops_profiler:
  enabled: false
  detailed: false
zero_optimization:
  stage: 2
  offload_optimizer:
    device: cpu
    pin_memory: true
  allgather_partitions: true
  allgather_bucket_size: 5e8
  overlap_comm: true
  reduce_scatter: true
  reduce_bucket_size: 5e8
  contiguous_gradients: true
  round_robin_gradients: true
